name: Upendra Shardanand
favicon: null
layout_spectrum: 0.26782
typography_spectrum: 0.86513
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcb52b'
    - '#fb8d25'
    - '#c03e16'
    - '#701907'
    - '#330201'
  brandStrength: 1
  lightness: 0.9375
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
